### ISSUE TITLE
Magento Connect Manager 404

### ISSUE THREAD

**Issue by Arrakeen** [Creare/magento-htaccess#14]
This htaccess causes a 404 error when we open the Magento Connect Manager link.

We are redirected to https://www.domain.tld/downloader/?return=https%3A%2F%2Fwww.domain.tld%2Findex.php%2Fadmin%2F, which is normal, but the content is fetched from the 404 page, not from the Mangento Connect Manager.

**Comment by IcyApril** [comment]
Hi;

This is due to the rules:

	RewriteCond %{THE_REQUEST} ^.*/index.php
	RewriteRule ^(.*)index.php$ http://www.yourdomain.com/$1 [R=301,L]

We are aware of this issue, in the past we have just commented this out when we need to reach Magento Connect; it has predated a lot of us at Creare (including me). I will look into applying a fix when I get a minute. 

Thanks for raising this and helping us build better open-source!

**Comment by IcyApril** [comment]
I have amended the file to now fix this issue. Please let us know if you find anything else or this gives you issues.

Thanks
